//! Static metadata describing DOTS struct types.
//!
//! These types are layout-aware: the [`StructDescriptor`] carries the
//! whole-struct `(size, align)` pair so dynamic instances ([`AnyStruct`])
//! can be heap-allocated with the same memory layout the proc-macro
//! produces for typed structs. Each [`PropertyDescriptor`] carries a
//! field offset and a [`PropertyVtable`] of typed thunks that read,
//! write, and drop the field through `*mut u8` pointers.
//!
//! The vtables are how the descriptor-driven codec stays user-type
//! agnostic at the runtime level: dotsd-style infrastructure walks the
//! descriptor and dispatches per-property without knowing the concrete
//! Rust types.
//!
//! [`AnyStruct`]: crate::layout::AnyStruct
//! [`PropertyVtable`]: PropertyVtable

use core::alloc::Layout;

use crate::layout::{CborDecoder, CborEncoder, DecodeError, EncodeError};

/// What kind of value lives behind a property's vtable.
///
/// This is metadata for introspection (e.g. logging, debugging,
/// cross-language tooling). The runtime codec dispatches via the
/// vtable thunks, not by matching on `FieldKind` — but `FieldKind`
/// is what survives a wire-only descriptor (one received over the
/// network without compiled thunks).
///
/// Equality compares structs by descriptor pointer identity, since
/// descriptors are `'static` and unique per type.
#[derive(Debug, Clone, Copy)]
pub enum FieldKind {
    Bool,
    U8, U16, U32, U64,
    I8, I16, I32, I64,
    F32, F64,
    String,
    Bytes,
    /// Homogeneous array of `inner`.
    Vec(&'static FieldKind),
    /// Nested DOTS struct, statically known at compile time.
    Struct(&'static StructDescriptor),
}

impl PartialEq for FieldKind {
    fn eq(&self, other: &Self) -> bool {
        use FieldKind::*;
        match (self, other) {
            (Bool, Bool) | (U8, U8) | (U16, U16) | (U32, U32) | (U64, U64)
            | (I8, I8) | (I16, I16) | (I32, I32) | (I64, I64)
            | (F32, F32) | (F64, F64)
            | (String, String) | (Bytes, Bytes) => true,
            (Vec(a), Vec(b)) => core::ptr::eq(*a, *b) || a == b,
            (Struct(a), Struct(b)) => core::ptr::eq(*a, *b),
            _ => false,
        }
    }
}

impl Eq for FieldKind {}

/// Per-property thunks operating on a typed `Option<T>` accessed via
/// raw pointer arithmetic from a struct base address.
///
/// Generated by `#[derive(DotsStruct)]` for each field. The thunks are
/// monomorphic — they know `T` — but expose a uniform pointer-based
/// interface so the descriptor-walker is type-agnostic.
///
/// All four functions are `unsafe fn`; the safety contract for each is
/// the same: the supplied pointer must point to a valid `Option<T>`
/// instance whose lifetime exceeds the call. A zero-initialized buffer
/// of the right `(size, align)` always satisfies this for `Option<T>`
/// because `None` is bit-pattern zero for every primitive `T` plus
/// `String`, `Vec<u8>`, `Vec<T>`, and `Box<_>` (niche optimization).
pub struct PropertyVtable {
    /// Layout of `Option<T>` for this property — used for sub-validation
    /// and (later) potential per-property allocation strategies.
    pub layout: Layout,

    /// Returns whether the property is `Some(_)`.
    pub is_set: unsafe fn(*const u8) -> bool,

    /// Reads the inner `T` (assumes `Some(_)`) and writes it to the
    /// encoder. Caller pre-counted via `is_set` so this is only called
    /// on populated fields.
    pub encode_value: unsafe fn(*const u8, &mut CborEncoder<'_>) -> Result<(), EncodeError>,

    /// Decodes a `T` from the decoder, drops any existing `Option<T>`
    /// at the destination, and writes `Some(value)` in its place.
    pub decode_value: unsafe fn(*mut u8, &mut CborDecoder<'_>) -> Result<(), DecodeError>,

    /// Drops the `Option<T>` at the pointer in place. Safe to call on
    /// a `None`, which is a no-op. Must be called exactly once per
    /// initialized field before the buffer is freed.
    pub drop_in_place: unsafe fn(*mut u8),
}

impl core::fmt::Debug for PropertyVtable {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("PropertyVtable")
            .field("layout", &self.layout)
            .finish_non_exhaustive()
    }
}

/// Compile-time metadata about a single DOTS property (one struct field).
#[derive(Debug)]
pub struct PropertyDescriptor {
    /// Field name in the source struct.
    pub name: &'static str,
    /// DOTS wire tag (1-based).
    pub tag: u32,
    /// Whether this property participates in the struct's primary key.
    pub is_key: bool,
    /// Byte offset from the parent struct's base — `offset_of!(Foo, field)`.
    pub offset: usize,
    /// Static type tag for introspection.
    pub kind: FieldKind,
    /// Typed read/write/drop thunks.
    pub vtable: &'static PropertyVtable,
}

/// Struct-level flags from the `.dots` model.
///
/// Stored as a packed `u8` so the whole `StructDescriptor` is `const`-constructible.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct StructFlags(u8);

impl StructFlags {
    const CACHED: u8 = 1 << 0;
    const INTERNAL: u8 = 1 << 1;
    const PERSISTENT: u8 = 1 << 2;
    const CLEANUP: u8 = 1 << 3;
    const LOCAL: u8 = 1 << 4;
    const SUBSTRUCT_ONLY: u8 = 1 << 5;

    pub const NONE: Self = Self(0);

    #[inline]
    pub const fn from_bits(bits: u8) -> Self {
        Self(bits)
    }

    #[inline]
    pub const fn bits(self) -> u8 {
        self.0
    }

    #[inline]
    pub const fn cached(self, on: bool) -> Self {
        Self(if on { self.0 | Self::CACHED } else { self.0 & !Self::CACHED })
    }
    #[inline]
    pub const fn internal(self, on: bool) -> Self {
        Self(if on { self.0 | Self::INTERNAL } else { self.0 & !Self::INTERNAL })
    }
    #[inline]
    pub const fn persistent(self, on: bool) -> Self {
        Self(if on { self.0 | Self::PERSISTENT } else { self.0 & !Self::PERSISTENT })
    }
    #[inline]
    pub const fn cleanup(self, on: bool) -> Self {
        Self(if on { self.0 | Self::CLEANUP } else { self.0 & !Self::CLEANUP })
    }
    #[inline]
    pub const fn local(self, on: bool) -> Self {
        Self(if on { self.0 | Self::LOCAL } else { self.0 & !Self::LOCAL })
    }
    #[inline]
    pub const fn substruct_only(self, on: bool) -> Self {
        Self(if on { self.0 | Self::SUBSTRUCT_ONLY } else { self.0 & !Self::SUBSTRUCT_ONLY })
    }

    #[inline]
    pub const fn is_cached(self) -> bool {
        (self.0 & Self::CACHED) != 0
    }
    #[inline]
    pub const fn is_internal(self) -> bool {
        (self.0 & Self::INTERNAL) != 0
    }
    #[inline]
    pub const fn is_persistent(self) -> bool {
        (self.0 & Self::PERSISTENT) != 0
    }
    #[inline]
    pub const fn is_cleanup(self) -> bool {
        (self.0 & Self::CLEANUP) != 0
    }
    #[inline]
    pub const fn is_local(self) -> bool {
        (self.0 & Self::LOCAL) != 0
    }
    #[inline]
    pub const fn is_substruct_only(self) -> bool {
        (self.0 & Self::SUBSTRUCT_ONLY) != 0
    }
}

/// Compile-time metadata about a DOTS struct.
///
/// Held as a `&'static StructDescriptor` constant on each generated type
/// (e.g. `MyType::DESCRIPTOR`). The `(size, align)` pair lets dynamic
/// `AnyStruct` instances allocate buffers whose layout matches the typed
/// struct exactly — so `&AnyStruct.data` is bit-identical with `&Foo`.
#[derive(Debug)]
pub struct StructDescriptor {
    pub name: &'static str,
    pub flags: StructFlags,
    /// `core::mem::size_of::<Foo>()` for the corresponding typed struct.
    pub size: usize,
    /// `core::mem::align_of::<Foo>()` for the corresponding typed struct.
    pub align: usize,
    pub properties: &'static [PropertyDescriptor],
}

impl StructDescriptor {
    /// Look up a property by tag. Linear scan — typically fewer than a
    /// dozen properties so this is fine.
    pub fn property(&self, tag: u32) -> Option<&'static PropertyDescriptor> {
        self.properties.iter().find(|p| p.tag == tag)
    }

    /// Iterate just the key properties.
    pub fn key_properties(&self) -> impl Iterator<Item = &'static PropertyDescriptor> {
        self.properties.iter().filter(|p| p.is_key)
    }

    /// `Layout` matching the typed struct — used by `AnyStruct::new` to
    /// allocate a layout-compatible buffer.
    pub fn layout(&self) -> Layout {
        // Safe by construction: `size` and `align` come from
        // `core::mem::size_of::<T>()` / `align_of::<T>()` of an actual
        // Rust type, which always satisfy `Layout`'s invariants.
        Layout::from_size_align(self.size, self.align)
            .expect("StructDescriptor size/align came from a real Rust type")
    }
}
