/// Compile-time metadata about a DOTS property (one struct field).
///
/// Generated by `#[derive(DotsStruct)]` and held in a `&'static [PropertyDescriptor]`
/// slice on the parent `StructDescriptor`.
#[derive(Debug, Clone, Copy)]
pub struct PropertyDescriptor {
    /// Field name in the source struct.
    pub name: &'static str,
    /// DOTS wire tag (1-based).
    pub tag: u32,
    /// Whether this property participates in the struct's primary key.
    pub is_key: bool,
    /// Display name of the inner type (`u32`, `String`, `Foo`, ...).
    /// Used for diagnostics; the runtime type system will replace this
    /// with a structured reference once the codec lands.
    pub type_name: &'static str,
}

/// Struct-level flags from the `.dots` model.
///
/// Stored as a packed `u8` so the whole `StructDescriptor` is `const`-constructible.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct StructFlags(u8);

impl StructFlags {
    const CACHED: u8 = 1 << 0;
    const INTERNAL: u8 = 1 << 1;
    const PERSISTENT: u8 = 1 << 2;
    const CLEANUP: u8 = 1 << 3;
    const LOCAL: u8 = 1 << 4;
    const SUBSTRUCT_ONLY: u8 = 1 << 5;

    pub const NONE: Self = Self(0);

    #[inline]
    pub const fn from_bits(bits: u8) -> Self {
        Self(bits)
    }

    #[inline]
    pub const fn bits(self) -> u8 {
        self.0
    }

    #[inline]
    pub const fn cached(self, on: bool) -> Self {
        Self(if on { self.0 | Self::CACHED } else { self.0 & !Self::CACHED })
    }
    #[inline]
    pub const fn internal(self, on: bool) -> Self {
        Self(if on { self.0 | Self::INTERNAL } else { self.0 & !Self::INTERNAL })
    }
    #[inline]
    pub const fn persistent(self, on: bool) -> Self {
        Self(if on { self.0 | Self::PERSISTENT } else { self.0 & !Self::PERSISTENT })
    }
    #[inline]
    pub const fn cleanup(self, on: bool) -> Self {
        Self(if on { self.0 | Self::CLEANUP } else { self.0 & !Self::CLEANUP })
    }
    #[inline]
    pub const fn local(self, on: bool) -> Self {
        Self(if on { self.0 | Self::LOCAL } else { self.0 & !Self::LOCAL })
    }
    #[inline]
    pub const fn substruct_only(self, on: bool) -> Self {
        Self(if on { self.0 | Self::SUBSTRUCT_ONLY } else { self.0 & !Self::SUBSTRUCT_ONLY })
    }

    #[inline]
    pub const fn is_cached(self) -> bool {
        (self.0 & Self::CACHED) != 0
    }
    #[inline]
    pub const fn is_internal(self) -> bool {
        (self.0 & Self::INTERNAL) != 0
    }
    #[inline]
    pub const fn is_persistent(self) -> bool {
        (self.0 & Self::PERSISTENT) != 0
    }
    #[inline]
    pub const fn is_cleanup(self) -> bool {
        (self.0 & Self::CLEANUP) != 0
    }
    #[inline]
    pub const fn is_local(self) -> bool {
        (self.0 & Self::LOCAL) != 0
    }
    #[inline]
    pub const fn is_substruct_only(self) -> bool {
        (self.0 & Self::SUBSTRUCT_ONLY) != 0
    }
}

/// Compile-time metadata about a DOTS struct.
///
/// Held as a `&'static StructDescriptor` constant on each generated type
/// (e.g. `MyType::DESCRIPTOR`). Const-constructible so the whole tree of
/// metadata is baked into the binary at zero runtime cost.
#[derive(Debug, Clone, Copy)]
pub struct StructDescriptor {
    pub name: &'static str,
    pub flags: StructFlags,
    pub properties: &'static [PropertyDescriptor],
}

impl StructDescriptor {
    /// Look up a property by tag. Linear scan — typically fewer than a
    /// dozen properties so this is fine; can be replaced with a perfect
    /// hash later if it ever shows up in profiles.
    pub fn property(&self, tag: u32) -> Option<&'static PropertyDescriptor> {
        self.properties.iter().find(|p| p.tag == tag)
    }

    /// Iterate just the key properties.
    pub fn key_properties(&self) -> impl Iterator<Item = &'static PropertyDescriptor> {
        self.properties.iter().filter(|p| p.is_key)
    }
}
