//! Minimal demo of the dots-rust type-system foundation.
//!
//! Shows three things:
//! 1. The `dots!` macro for terse partial-object literals.
//! 2. The `with_*` builder methods generated by `#[derive(DotsStruct)]`.
//! 3. The runtime descriptor + `valid_set()` derived from `Option<T>` state.

use dots_core::{StructValue, dots};
use dots_derive::DotsStruct;

#[derive(DotsStruct, Default, Debug)]
#[dots(name = "RoundtripData", cached, persistent)]
struct RoundtripData {
    #[dots(tag = 1, key)]
    id: Option<u32>,

    #[dots(tag = 2)]
    payload: Option<String>,

    #[dots(tag = 3)]
    counter: Option<u64>,

    #[dots(tag = 4)]
    flag: Option<bool>,
}

fn print_summary<T: StructValue + std::fmt::Debug>(label: &str, value: &T) {
    let d = value.descriptor();
    println!("--- {label} ---");
    println!("  type:       {}", d.name);
    println!("  cached:     {}", d.flags.is_cached());
    println!("  persistent: {}", d.flags.is_persistent());
    println!("  valid_set:  {:?}", value.valid_set());
    println!("  value:      {value:?}");
}

fn main() {
    // Construction via the global `dots!` macro.
    // Note `9000_u64` — non-i32 integers need a type suffix because the
    // macro routes through `.into()` (see dots_core::dots docs).
    let from_macro = dots!(RoundtripData {
        id: 42_u32,
        payload: "hello",
        counter: 9000_u64,
    });
    print_summary("from dots! macro", &from_macro);

    // Construction via builder methods.
    let from_builder = RoundtripData::default()
        .with_id(7_u32)
        .with_payload("world")
        .with_flag(true);
    print_summary("from builder", &from_builder);

    // Field access — accessors return Option<&T>.
    let id_ref: Option<&u32> = from_macro.id();
    let payload_ref: Option<&str> = from_macro.payload().map(String::as_str);
    println!();
    println!("from_macro.id() = {id_ref:?}");
    println!("from_macro.payload() = {payload_ref:?}");
    println!("from_macro.has_flag() = {}", from_macro.has_flag());

    // Inspect the static descriptor.
    println!();
    println!("descriptor properties:");
    for p in RoundtripData::DESCRIPTOR.properties {
        println!(
            "  tag {:>2}  {:<10}  {:<10}  key={}",
            p.tag, p.name, p.type_name, p.is_key
        );
    }

    // Demonstrate type erasure: hand a `&dyn StructValue` to a generic site.
    let erased: &dyn StructValue = &from_macro;
    println!();
    println!(
        "via dyn StructValue: name={}, valid_set={:?}",
        erased.descriptor().name,
        erased.valid_set()
    );

    // Downcast back to the concrete type.
    let downcast: Option<&RoundtripData> = erased.as_any().downcast_ref::<RoundtripData>();
    assert!(downcast.is_some(), "downcast must succeed");
    println!("downcast roundtrip: ok");
}
